service:
  webmail-worker-rmq:
    image: rjyspl/webmail-worker-rmq:latest
    container_name: webmail-worker-rmq

    env_file: 
      - .env

    volumes:
      - ./logs:/app/logs

    restart: always